= Gauche Bluesky API library

A convenience library to access link:https://bsky.app/[Bluesky] API.

== Prerequisites

link:https://practical-scheme.net/gauche[Gauche] 0.9.13 or later

You need to have Bluesky handle and its app password.  The first thing
you do is to call `make-bsky-session` with those parameters to obtain
a `<bsky-session>` object, which can be used for subsequent API calls.

== API

=== Creating a session

`(make-bsky-session :optional handle app-password)` accesses `bsky.app`
to get a session token.  Returns `<bsky-session>` on success.
Throws `<bsky-error>` condition if something goes wrong.

If _handle_ and/or _app-password_ is omitted, values of the environment
variable `GAUCHE_BSKY_HANDLE` and `GAUCHE_BSKY_APP_PASSWORD`
are used, respectively.

=== Retrieving a post

You need to know the _rkey_ to retrieve a post.  _Rkey_ is
shown in the last part of the post's URL.

`(bsky-get-record session rkey)` returns `<bsky-record>` of the post.

=== Posting a text

Currently, only a simple text posting is supported.

`(bsky-post-text session text :key created-at langs quote-post reply)` posts _text_.

- _Created-at_ is the post's timestamp, and the current time is used when
omitted.
- _Langs_ must be a list of language tags (e.g. `"en_US"` or `"ja"`).
- _Quoted-post_ must be a `<bsky-record>` of the post to quote.
- _Reply_ must be a two-element list of `<bsky-record>`, the first
element is the root post of the thread, and the second element
is the direct parent of the post.


=== Error handling

If Bluesky API call fails, a condition of type `<bsky-error>` is thrown.
Along with the error message in the API response, the condition
has the following slots.

- `status-code`: String HTTP status code.
- `http-headers`: List of http response headers, in the form as
`http-get` or `http-post` returned.
- `payload`: If the response is in JSON, a parsed JSON structure.  Otherwise, a string of the response body.

You can throw `<bsky-error>` with `(bsky-error status-code http-headers body)`.
